<?php
/**
 * OpenSIS Database Configuration
 * Generated by installer
 */

// Get database credentials from environment variables
$db_server = getenv('MYSQL_HOST') ?: 'mysql.railway.internal';
$db_port = getenv('MYSQL_PORT') ?: '3306';
$db_user = getenv('MYSQL_USER') ?: 'root';
$db_pass = getenv('MYSQL_PASSWORD') ?: '';
$db_name = getenv('MYSQL_DATABASE') ?: 'opensis';

// Define database constants for OpenSIS
define('DatabaseServer', $db_server);
define('DatabasePort', $db_port);
define('DatabaseUsername', $db_user);
define('DatabasePassword', $db_pass);
define('DatabaseName', $db_name);
define('DatabaseType', 'mysqli');

// Create database connection
$connection = @new mysqli(
    DatabaseServer,
    DatabaseUsername,
    DatabasePassword,
    DatabaseName,
    DatabasePort
);

// Check connection
if ($connection->connect_errno) {
    error_log("OpenSIS Database Connection Error: " . $connection->connect_error);
    die('<h1>Database Connection Error</h1><p>Could not connect to database. Please check your configuration.</p>');
}

// Set charset to UTF-8
$connection->set_charset('utf8mb4');

// For backward compatibility with older OpenSIS code
if (!isset($DatabaseConnection)) {
    $DatabaseConnection = $connection;
}

// System configuration
if (!defined('Config')) {
    define('Config', true);
}

// Timezone
date_default_timezone_set('America/New_York');

// Error reporting based on environment
if (getenv('RAILWAY_ENVIRONMENT') === 'production') {
    error_reporting(0);
    ini_set('display_errors', '0');
} else {
    error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);
    ini_set('display_errors', '1');
}

// Session configuration
if (!session_id()) {
    ini_set('session.use_cookies', 1);
    ini_set('session.use_only_cookies', 1);
    ini_set('session.cookie_httponly', 1);
    session_name('openSIS_SESSION');
}
?>
```

## Verificar Variables de Entorno en Railway

Asegúrate de que en Railway → Tu servicio OpenSIS → **Variables** tengas:
```
MYSQL_HOST=mysql.railway.internal
MYSQL_PORT=3306
MYSQL_DATABASE=opensis
MYSQL_USER=root
MYSQL_PASSWORD=[tu contraseña de MySQL de Railway]
